### ISSUE TITLE
Next mow offset automation

### ISSUE THREAD

**Issue by karaspr** [jm-73/Indego#105]
how to code automation triggered some given time before next mow? I would like to be reminded to clean the lawn before mower cuts small object in pieces :)

**Comment by jm-73** [comment]
I think this is best suited for a package in HA. This is not possible to integrate in this custom integration 8as far as I know)

**Comment by eavanvalkenburg** [comment]
@karaspr you can create a automation trigger with a template, would need a sensor.time to help, and then compare with your offset to that, see the discussion here: https://community.home-assistant.io/t/solved-time-trigger-with-input-datetime-not-working/86239/2?u=eavanvalkenburg

**Comment by UltraSub** [comment]
I use this for grabbing the Alexa alarm and offsetting for triggering my wake up routine:
```yaml
- platform: template
  sensors:
    alexa_bedroom_minutes_to_alarm:
      entity_id: sensor.date_time
      value_template: >
        {% if is_state('sensor.echo_show_next_alarm', 'unavailable')  %}
          No alarm set
        {% else %}
          {{ (((as_timestamp(strptime(states("sensor.echo_show_next_alarm"), "%Y-%m-%d %H:%M:%S%z"))) - as_timestamp( strptime( now().strftime("%Y-%m-%d %H:%M:%S%z"), "%Y-%m-%d %H:%M:%S%z") )) / 60) | int}}
        {% endif %}
      friendly_name: 'Minutes to alarm'
```

And then an automation to trigger the lights, same can be done for notification of course:
```yaml
- alias: 'Wake-up Lights'
  trigger:
    - platform: state
      entity_id: sensor.alexa_bedroom_minutes_to_alarm
      to: '30'
  action:
    - service: script.turn_on
      entity_id: script.wakeup_bedroom
```
