### ISSUE TITLE
Deleting alerts on multiple mowers

### ISSUE THREAD

**Issue by RolandE1204** [jm-73/Indego#211]
I do have multiple mowers and want to delete all alerts from one of the mowers. indego.delete_alert_all is not working. How can I do this?

**Comment by kimzeuner** [comment]
Here are the changes that you can test.
1. in custom_components/indego/services.yaml
  add the folowing code to all 4 alert features 
```
    mower_serial:
      description: The serial of the mower for this action. Only required when you have multiple mowers configured.
      example: '"0123456789"'
      required: false
```
it should look like this (here as an example for the service "delete alert", as i said you have to repeat this for the other 3 alert features)
```
delete_alert:
  description: Delete the selected Alert
  fields:
    mower_serial:
      description: The serial of the mower for this action. Only required when you have multiple mowers configured.
      example: '"0123456789"'
      required: false
    alert_index: 
      description: Delete the selected Alert in this case the latest
      example: "0"
```

2. in custom_components/indego/__init__.py search for "SERVICE_SCHEMA_DELETE_ALERT = vol.Schema({"
and add the line 
```
vol.Optional(CONF_MOWER_SERIAL): cv.string,
```
so it should look like this
```
SERVICE_SCHEMA_DELETE_ALERT = vol.Schema({
    vol.Optional(CONF_MOWER_SERIAL): cv.string,
    vol.Required(CONF_DELETE_ALERT): cv.positive_int
})
```
again repeat that for the other 3 alert features.

3. in custom_components/indego/__init__.py search for "async def async_delete_alert(call):" and change the code from 
```
    async def async_delete_alert(call):
        """Handle the service call."""
        enable = call.data.get(CONF_DELETE_ALERT, DEFAULT_NAME_COMMANDS)
        _LOGGER.debug("Indego.delete_alert service called, with command: %s", enable)
        await hass.data[DOMAIN][entry.entry_id]._update_alerts()
        await hass.data[DOMAIN][entry.entry_id]._indego_client.delete_alert(enable)
        await hass.data[DOMAIN][entry.entry_id]._update_alerts()     
```

to 
```
    async def async_delete_alert(call):
        """Handle the service call."""
        instance = find_instance_for_mower_service_call(call)
        enable = call.data.get(CONF_DELETE_ALERT, DEFAULT_NAME_COMMANDS)
        _LOGGER.debug("Indego.delete_alert service called, with command: %s", enable)
        await instance._update_alerts()
        await instance._indego_client.delete_alert(enable)
        await instance._update_alerts()    
```
also here you have to repeat this for the other 3 alert features. important is to add the line
```
instance = find_instance_for_mower_service_call(call)
```
and change 
```
hass.data[DOMAIN][entry.entry_id].
```
to 
```
 instance.
```

As an alternative you can download the files 
[__init__.py](https://github.com/kimzeuner/Indego/blob/53906b0e9b546c5b788417a36bcbdc7a8202627c/custom_components/indego/__init__.py)
and [services.yaml](https://github.com/jm-73/Indego/blob/e84188165625404bb72fe094449cb9f5ba4c7b52/custom_components/indego/services.yaml)
copy them to your custom_components/indego folder and replace the old ones.

After you made the changes restart Home Assistant.

Please let me know if it works.
