### ISSUE TITLE
created sensors vs avaialble attributes

### ISSUE THREAD

**Issue by jjanderson** [jm-73/Indego#79]
Hi,

I was just wondering if you could update the readme to define which sensors are created automatically by the component and then which are available in the attributes?

I have been using this for over a year now. I initially created tempalte sensors as such:

```
    indego_battery_temp:
      friendly_name: 'Battery Temperature'
      value_template: "{{state_attr('sensor.indego_battery', 'Battery temp')}}"
      unit_of_measurement: '°C'

    indego_last_session_total:
      friendly_name: 'Last session operating'
      value_template: "{{state_attr('sensor.indego_lawn_mowed', 'Last session Operation')}}"
      unit_of_measurement: 'Minutes'

    indego_last_session_cutting:
      friendly_name: 'Last session cutting'
      value_template: "{{state_attr('sensor.indego_lawn_mowed', 'Last session Cut')}}"
      unit_of_measurement: 'Minutes'

    indego_last_session_charging:
      friendly_name: 'Last session charging'
      value_template: "{{state_attr('sensor.indego_lawn_mowed', 'Last session Charge')}}"
      unit_of_measurement: 'Minutes'

    indego_total_mowing:
      friendly_name: 'Total Mowing'
      value_template: "{{state_attr('sensor.indego_runtime_total', 'Total mowing time')}}"
      unit_of_measurement: 'h'

    indego_total_charging:
      friendly_name: 'Total Charging'
      value_template: "{{state_attr('sensor.indego_runtime_total', 'Total charging time')}}"
      unit_of_measurement: 'h'
```

but I am wanting to do a little housekeeping and want to know if I should essentially still keep these template sensors or of the sensors are automatically now generated with the component

Thanks again for all your help!
